# -*- coding: utf-8 -*-
from __future__ import annotations


def render_main_content_inner(
    *,
    ui,
    state,
    sidebar_content,
    render_canvas_toolbar,
    nacrt_render,
    main_content_refresh,
    set_view_mode,
    set_show_grid,
    set_grid_mm,
    set_show_bounds,
    set_ceiling_filler,
    render_kitchen_elements_scene_3d,
    wall_len_h,
    zone_baseline_and_height,
    get_zone_depth_standard,
    render_elements_tab,
    render_cutlist_tab,
    pd,
    plt,
    build_cutlist_sections,
    generate_cutlist_excel,
    build_pdf_bytes,
    render_fn,
    fig_to_data_uri_exact,
    render_element_preview,
    svg_for_tid,
    assembly_instructions,
    render_settings_tab,
    set_zone_depth_standard,
    nacrt_refresh,
    set_front_color,
    set_material,
    set_wall_length,
    set_wall_height,
    set_foot_height,
    set_worktop_thickness,
    set_base_height,
    set_worktop_width,
    set_vertical_gap,
    set_max_element_height,
    render_color_picker,
    render_nova_tab,
    switch_tab,
    clear_all_local,
    save_project_json,
    load_project_json,
    render_help_tab,
    render_wizard_tab,
    main_content,
    render_room_setup_step3,
    ensure_room_walls,
    get_room_wall,
    room_opening_types,
    room_fixture_types,
) -> None:
    if state.active_tab == "elementi":
        render_elements_tab(
            ui=ui,
            state=state,
            sidebar_content=sidebar_content,
            render_canvas_toolbar=render_canvas_toolbar,
            nacrt_render=nacrt_render,
            main_content_refresh=main_content_refresh,
            set_view_mode=set_view_mode,
            set_show_grid=set_show_grid,
            set_grid_mm=set_grid_mm,
            set_show_bounds=set_show_bounds,
            set_ceiling_filler=set_ceiling_filler,
            render_kitchen_elements_scene_3d=render_kitchen_elements_scene_3d,
            wall_len_h=wall_len_h,
            zone_baseline_and_height=zone_baseline_and_height,
            get_zone_depth_standard=get_zone_depth_standard,
        )
    elif state.active_tab == "krojna":
        render_cutlist_tab(
            ui=ui,
            state=state,
            pd=pd,
            plt=plt,
            build_cutlist_sections=build_cutlist_sections,
            generate_cutlist_excel=generate_cutlist_excel,
            build_pdf_bytes=build_pdf_bytes,
            wall_len_h=wall_len_h,
            render_fn=render_fn,
            fig_to_data_uri_exact=fig_to_data_uri_exact,
            render_element_preview=render_element_preview,
            svg_for_tid=svg_for_tid,
            assembly_instructions=assembly_instructions,
        )
        return
    elif state.active_tab == "podesavanja":
        render_settings_tab(
            ui=ui,
            state=state,
            get_zone_depth_standard=get_zone_depth_standard,
            set_zone_depth_standard=set_zone_depth_standard,
            nacrt_refresh=nacrt_refresh,
            main_content_refresh=main_content_refresh,
            set_front_color=set_front_color,
            set_material=set_material,
            set_wall_length=set_wall_length,
            set_wall_height=set_wall_height,
            set_foot_height=set_foot_height,
            set_worktop_thickness=set_worktop_thickness,
            set_base_height=set_base_height,
            set_worktop_width=set_worktop_width,
            set_vertical_gap=set_vertical_gap,
            set_max_element_height=set_max_element_height,
            render_color_picker=render_color_picker,
        )
        return
    elif state.active_tab == "nova":
        render_nova_tab(
            ui=ui,
            state=state,
            main_content_refresh=main_content_refresh,
            switch_tab=switch_tab,
            clear_all_local=clear_all_local,
            save_project_json=save_project_json,
            load_project_json=load_project_json,
        )
        return
    elif state.active_tab == "pomoc":
        render_help_tab(ui=ui)
        return
    elif state.active_tab == "wizard":
        render_wizard_tab(
            ui=ui,
            state=state,
            main_content=main_content,
            main_content_refresh=main_content_refresh,
            switch_tab=switch_tab,
            render_room_setup_step3=render_room_setup_step3,
            plt=plt,
            ensure_room_walls=ensure_room_walls,
            get_room_wall=get_room_wall,
            set_wall_length=set_wall_length,
            set_wall_height=set_wall_height,
            room_opening_types=room_opening_types,
            room_fixture_types=room_fixture_types,
        )
        return

